package httpapi

import (
	"net/http"
	"path/filepath"
)

func NewRouter(handlers *Handlers, staticDir string) http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /healthz", handlers.Healthz)
	mux.HandleFunc("GET /api/groups", handlers.APIGroups)
	mux.HandleFunc("GET /api/groups/{group_name}/standings", handlers.APIGroupStandings)
	mux.HandleFunc("POST /api/rpc", handlers.StandingsRPC)
	mux.HandleFunc("GET /standings/admin", handlers.AdminAuth(handlers.AdminPage))
	mux.HandleFunc("GET /standings/admin/files", handlers.AdminAuth(handlers.AdminFilesPage))
	mux.HandleFunc("GET /standings/admin/logs", handlers.AdminAuth(handlers.AdminLogsPage))
	mux.HandleFunc("GET /standings/admin/group-accounts", handlers.AdminAuth(handlers.AdminGroupAccounts))
	mux.HandleFunc("GET /standings/admin/group-grades", handlers.AdminAuth(handlers.AdminGroupGradesPage))
	mux.HandleFunc("POST /api/admin/group-grades/save", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupGradesSave))))
	mux.HandleFunc("POST /api/admin/group-grades/config-save", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupGradesConfigSave))))
	mux.HandleFunc("GET /standings/admin/students", handlers.AdminAuth(handlers.AdminStudentsPage))
	mux.HandleFunc("GET /standings/admin/student", handlers.AdminAuth(handlers.AdminStudentProfilePage))
	mux.HandleFunc("POST /api/admin/students/save", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminStudentSave))))
	mux.HandleFunc("POST /api/admin/students/delete", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminStudentDelete))))
	mux.HandleFunc("GET /standings/admin/group", handlers.AdminAuth(handlers.AdminGroupManagePage))
	mux.HandleFunc("POST /api/admin/group/members/remove", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupMemberRemove))))
	mux.HandleFunc("POST /api/admin/group/register-names/dry-run", handlers.AdminAuth(handlers.AdminGroupRegisterNamesDryRun))
	mux.HandleFunc("POST /api/admin/group/register-names/apply", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupRegisterNamesApply))))
	mux.HandleFunc("POST /api/admin/group/accesses/save", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupAccessesSave)))
	mux.HandleFunc("POST /api/admin/global-accesses/save", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGlobalAccessesSave)))
	mux.HandleFunc("POST /api/admin/group/form-link/set", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupSetFormLink))))
	mux.HandleFunc("POST /api/admin/group/short-name/set", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupSetShortName))))
	mux.HandleFunc("POST /api/admin/group/archive/set", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupSetArchived))))
	mux.HandleFunc("POST /api/admin/group/show-task-links/set", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupSetShowTaskLinks))))
	mux.HandleFunc("POST /api/admin/group/contests/add-ref", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupContestAddRef))))
	mux.HandleFunc("POST /api/admin/group/contests/remove", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupContestRemove))))
	mux.HandleFunc("POST /api/admin/group/contests/move", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupContestMove))))
	mux.HandleFunc("POST /api/admin/group/contests/set-options", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupContestSetOptions))))
	mux.HandleFunc("POST /api/admin/group/contests/inline-save", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupContestInlineSave))))
	mux.HandleFunc("GET /standings/admin/contests", handlers.AdminAuth(handlers.AdminContestsPage))
	mux.HandleFunc("POST /api/admin/contests/save", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminContestSave))))
	mux.HandleFunc("POST /api/admin/contests/delete", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminContestDelete))))
	mux.HandleFunc("POST /api/admin/actions/generate", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.AdminActionGenerate)))
	mux.HandleFunc("POST /api/admin/actions/reset-cache", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.AdminActionResetCache)))
	mux.HandleFunc("GET /standings/admin/export", handlers.AdminAuth(handlers.AdminExportPage))
	mux.HandleFunc("POST /api/admin/export/download", handlers.AdminAuth(handlers.AdminExportDownload))
	mux.HandleFunc("GET /standings/admin/import", handlers.AdminAuth(handlers.AdminImportPage))
	mux.HandleFunc("POST /api/admin/import/apply", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminImportApply))))
	mux.HandleFunc("GET /standings/admin/intake", handlers.AdminAuth(handlers.AdminIntakePage))
	mux.HandleFunc("POST /api/admin/actions/intake/prepare", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminIntakeStagingPrepare))))
	mux.HandleFunc("POST /api/admin/actions/intake/dry-run", handlers.AdminAuth(handlers.AdminIntakeMergeDryRun))
	mux.HandleFunc("POST /api/admin/actions/intake/merge", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminIntakeStagingMerge))))
	mux.HandleFunc("POST /api/admin/groups/create", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminGroupCreate))))
	mux.HandleFunc("POST /api/admin/combined/save", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminCombinedGroupSave))))
	mux.HandleFunc("POST /api/admin/combined/delete", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminCombinedGroupDelete))))
	mux.HandleFunc("GET /standings/admin/combined", handlers.AdminAuth(handlers.AdminCombinedManagePage))
	mux.HandleFunc("POST /api/admin/combined/set-contest-hidden", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminCombinedSetContestHidden))))
	mux.HandleFunc("GET /api/admin/files", handlers.AdminAuth(handlers.AdminFiles))
	mux.HandleFunc("GET /api/admin/file", handlers.AdminAuth(handlers.AdminFile))
	mux.HandleFunc("POST /api/admin/file/validate", handlers.AdminAuth(handlers.AdminFileValidate))
	mux.HandleFunc("POST /api/admin/file/save", handlers.AdminAuth(handlers.AuditAdminWrite(handlers.SerializeDataWrite(handlers.AdminFileSave))))
	// Операции доступов группы: права проверяются внутри хендлеров по токену в
	// адресе или куке сессии (см. access_resolve.go). В журнал пишут сами
	// хендлеры — им есть что сказать по делу, обёртка AuditAdminWrite не нужна.
	mux.HandleFunc("POST /api/admin/flags/review", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminFlagReviewSet)))
	mux.HandleFunc("POST /api/jury/flags/review", handlers.SerializeDataWrite(handlers.JuryFlagReviewSet))
	mux.HandleFunc("POST /api/jury/group/konduit/save", handlers.SerializeDataWrite(handlers.JuryKonduitSave))
	mux.HandleFunc("POST /api/jury/group/konduit/create", handlers.SerializeDataWrite(handlers.JuryKonduitCreate))
	mux.HandleFunc("GET /standings/{group_name}/jury-konduit", handlers.JuryKonduitPage)

	// Вход по логину и паролю: /panel спрашивает учётку (Basic Auth), выдаёт
	// куку сессии и показывает страницу группы с правами вошедшего.
	mux.HandleFunc("GET /standings/{group_name}/panel", handlers.GroupPanelPage)
	mux.HandleFunc("GET /standings/signout", handlers.AccessSignOut)
	mux.HandleFunc("GET /standings/{group_name}/manage/contests", handlers.GroupManageContestsPage)
	mux.HandleFunc("GET /standings/{group_name}/manage/grades", handlers.GroupManageGradesPage)
	mux.HandleFunc("POST /api/group-panel/contests/add-ref", handlers.SerializeDataWrite(handlers.PanelContestAddRef))
	mux.HandleFunc("POST /api/group-panel/contests/remove", handlers.SerializeDataWrite(handlers.PanelContestRemove))
	mux.HandleFunc("POST /api/group-panel/contests/move", handlers.SerializeDataWrite(handlers.PanelContestMove))
	mux.HandleFunc("POST /api/group-panel/contests/set-options", handlers.SerializeDataWrite(handlers.PanelContestSetOptions))
	mux.HandleFunc("POST /api/group-panel/contests/inline-save", handlers.SerializeDataWrite(handlers.PanelContestInlineSave))
	mux.HandleFunc("POST /api/group-panel/group-grades/save", handlers.SerializeDataWrite(handlers.PanelGradesSave))
	mux.HandleFunc("POST /api/group-panel/group-grades/config-save", handlers.SerializeDataWrite(handlers.PanelGradesConfigSave))
	mux.HandleFunc("GET /standings", handlers.IndexPage)
	mux.HandleFunc("GET /standings/{group_name}", handlers.GroupStandingsPage)
	mux.HandleFunc("GET /standings/{group_name}/grades", handlers.GroupGradesPage)
	mux.HandleFunc("GET /standings/{group_name}/participants", handlers.GroupParticipantsPage)
	mux.HandleFunc("GET /standings/{group_name}/student", handlers.GroupStudentProfilePage)
	mux.HandleFunc("GET /standings/{group_name}/summary", handlers.GroupSummaryAllPage)
	mux.HandleFunc("GET /standings/{group_name}/summary-data", handlers.GroupSummaryData)
	mux.HandleFunc("GET /standings/{group_name}/contest-fragment", handlers.GroupContestFragment)
	mux.HandleFunc("GET /standings/{group_name}/contest", handlers.GroupContestPage)
	mux.HandleFunc("GET /standings/{group_name}/summary-edu", handlers.GroupSummaryEduPage)
	mux.HandleFunc("GET /standings/{group_name}/summary-olymp", handlers.GroupSummaryOlympPage)
	mux.HandleFunc("GET /standings/{group_name}/export.xlsx", handlers.GroupExportXLSX)
	mux.HandleFunc("GET /api/admin/group/export.xlsx", handlers.AdminAuth(handlers.AdminGroupExportXLSX))
	mux.HandleFunc("GET /favicon.ico", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, filepath.Join(staticDir, "favicon.ico"))
	})
	mux.HandleFunc("GET /apple-touch-icon.png", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, filepath.Join(staticDir, "apple-touch-icon.png"))
	})

	staticFS := http.FileServer(http.Dir(staticDir))
	mux.Handle("GET /static/", http.StripPrefix("/static/", staticFS))

	return mux
}
