package httpapi

import (
	"net/http"
	"path/filepath"
)

func NewRouter(handlers *Handlers, staticDir string) http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /healthz", handlers.Healthz)
	mux.HandleFunc("GET /api/groups", handlers.APIGroups)
	mux.HandleFunc("GET /api/groups/{group_name}/standings", handlers.APIGroupStandings)
	mux.HandleFunc("POST /api/rpc", handlers.StandingsRPC)
	mux.HandleFunc("GET /standings/admin", handlers.AdminAuth(handlers.AdminPage))
	mux.HandleFunc("GET /standings/admin/group-accounts", handlers.AdminAuth(handlers.AdminGroupAccounts))
	mux.HandleFunc("GET /standings/admin/group-grades", handlers.AdminAuth(handlers.AdminGroupGradesPage))
	mux.HandleFunc("POST /api/admin/group-grades/save", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupGradesSave)))
	mux.HandleFunc("POST /api/admin/group-grades/config-save", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupGradesConfigSave)))
	mux.HandleFunc("GET /standings/admin/students", handlers.AdminAuth(handlers.AdminStudentsPage))
	mux.HandleFunc("GET /standings/admin/student", handlers.AdminAuth(handlers.AdminStudentProfilePage))
	mux.HandleFunc("POST /api/admin/students/save", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminStudentSave)))
	mux.HandleFunc("POST /api/admin/students/delete", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminStudentDelete)))
	mux.HandleFunc("GET /standings/admin/group", handlers.AdminAuth(handlers.AdminGroupManagePage))
	mux.HandleFunc("POST /api/admin/group/members/remove", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupMemberRemove)))
	mux.HandleFunc("POST /api/admin/group/token/set", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupTokenSet)))
	mux.HandleFunc("POST /api/admin/group/short-name/set", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupSetShortName)))
	mux.HandleFunc("POST /api/admin/group/show-task-links/set", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupSetShowTaskLinks)))
	mux.HandleFunc("POST /api/admin/group/contests/add-ref", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupContestAddRef)))
	mux.HandleFunc("POST /api/admin/group/contests/remove", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupContestRemove)))
	mux.HandleFunc("POST /api/admin/group/contests/move", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupContestMove)))
	mux.HandleFunc("POST /api/admin/group/contests/set-options", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupContestSetOptions)))
	mux.HandleFunc("POST /api/admin/group/contests/inline-save", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupContestInlineSave)))
	mux.HandleFunc("GET /standings/admin/contests", handlers.AdminAuth(handlers.AdminContestsPage))
	mux.HandleFunc("POST /api/admin/contests/save", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminContestSave)))
	mux.HandleFunc("POST /api/admin/contests/delete", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminContestDelete)))
	mux.HandleFunc("POST /api/admin/actions/generate", handlers.AdminAuth(handlers.AdminActionGenerate))
	mux.HandleFunc("POST /api/admin/actions/reset-cache", handlers.AdminAuth(handlers.AdminActionResetCache))
	mux.HandleFunc("GET /standings/admin/export", handlers.AdminAuth(handlers.AdminExportPage))
	mux.HandleFunc("POST /api/admin/export/download", handlers.AdminAuth(handlers.AdminExportDownload))
	mux.HandleFunc("GET /standings/admin/import", handlers.AdminAuth(handlers.AdminImportPage))
	mux.HandleFunc("POST /api/admin/import/apply", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminImportApply)))
	mux.HandleFunc("POST /api/admin/actions/intake/prepare", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminIntakeStagingPrepare)))
	mux.HandleFunc("POST /api/admin/actions/intake/dry-run", handlers.AdminAuth(handlers.AdminIntakeMergeDryRun))
	mux.HandleFunc("POST /api/admin/actions/intake/merge", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminIntakeStagingMerge)))
	mux.HandleFunc("POST /api/admin/groups/create", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminGroupCreate)))
	mux.HandleFunc("POST /api/admin/combined/save", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminCombinedGroupSave)))
	mux.HandleFunc("POST /api/admin/combined/delete", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminCombinedGroupDelete)))
	mux.HandleFunc("GET /standings/admin/combined", handlers.AdminAuth(handlers.AdminCombinedManagePage))
	mux.HandleFunc("POST /api/admin/combined/set-contest-hidden", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminCombinedSetContestHidden)))
	mux.HandleFunc("GET /api/admin/files", handlers.AdminAuth(handlers.AdminFiles))
	mux.HandleFunc("GET /api/admin/file", handlers.AdminAuth(handlers.AdminFile))
	mux.HandleFunc("POST /api/admin/file/validate", handlers.AdminAuth(handlers.AdminFileValidate))
	mux.HandleFunc("POST /api/admin/file/save", handlers.AdminAuth(handlers.SerializeDataWrite(handlers.AdminFileSave)))
	// Жюри-панель: операции по group_secret_token (авторизация внутри хендлеров).
	mux.HandleFunc("POST /api/jury/group/contests/add-ref", handlers.SerializeDataWrite(handlers.JuryContestAddRef))
	mux.HandleFunc("POST /api/jury/group/contests/move", handlers.SerializeDataWrite(handlers.JuryContestMove))
	mux.HandleFunc("POST /api/jury/group/grades/save", handlers.SerializeDataWrite(handlers.JuryGradesSave))
	mux.HandleFunc("POST /api/jury/group/konduit/save", handlers.SerializeDataWrite(handlers.JuryKonduitSave))
	mux.HandleFunc("POST /api/jury/group/konduit/create", handlers.SerializeDataWrite(handlers.JuryKonduitCreate))
	mux.HandleFunc("GET /standings/{group_name}/jury-grades", handlers.JuryGradesPage)
	mux.HandleFunc("GET /standings/{group_name}/jury-konduit", handlers.JuryKonduitPage)
	mux.HandleFunc("GET /standings", handlers.IndexPage)
	mux.HandleFunc("GET /standings/{group_name}", handlers.GroupStandingsPage)
	mux.HandleFunc("GET /standings/{group_name}/grades", handlers.GroupGradesPage)
	mux.HandleFunc("GET /standings/{group_name}/participants", handlers.GroupParticipantsPage)
	mux.HandleFunc("GET /standings/{group_name}/student", handlers.GroupStudentProfilePage)
	mux.HandleFunc("GET /standings/{group_name}/summary", handlers.GroupSummaryAllPage)
	mux.HandleFunc("GET /standings/{group_name}/summary-edu", handlers.GroupSummaryEduPage)
	mux.HandleFunc("GET /standings/{group_name}/summary-olymp", handlers.GroupSummaryOlympPage)
	mux.HandleFunc("GET /favicon.ico", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, filepath.Join(staticDir, "favicon.ico"))
	})
	mux.HandleFunc("GET /apple-touch-icon.png", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, filepath.Join(staticDir, "apple-touch-icon.png"))
	})

	staticFS := http.FileServer(http.Dir(staticDir))
	mux.Handle("GET /static/", http.StripPrefix("/static/", staticFS))

	return mux
}
